export async function onRequest() {
  return Response.json({ sources: [
    'Reuters Markets',
    'Reuters Economy',
    'World Economy Search',
    'IMF World Bank Search',
    'BBC World',
    'BBC Business RSS',
    'Guardian World',
    'Guardian Business',
    'Al Jazeera World',
    'DW World',
    'France24 World',
    'UN News Global',
    'Global Conflict Search',
    'Ukraine War Search',
    'Middle East War Search',
    'Red Sea Shipping Risk',
    'Sanctions Economy Search',
    'Reuters Trump',
    'AP Trump',
    'MSN News',
    'MSN Money',
    'Daily Mail',
    'BBC Business',
    'CNBC Markets',
    'Yahoo Finance',
    'MarketWatch',
    'FXStreet',
    'ForexLive',
    'OilPrice',
    'CoinDesk',
    'Cointelegraph',
    'Iraq Latest',
    'Iraq Economy',
    'Iraq Oil',
    'Iraq Dinar CBI',
    'Kurdistan Region',
    'Rudaw Search',
    'Shafaq Search',
    'Iraqi News Search',
    'Iraq Business Search',
    'Shafaq News',
    'Rudaw',
    'Kurdistan24',
    'Iraq Business News',
    'Central Bank of Iraq monitoring',
    'Truth Social monitoring'
  ] }, { headers: { 'Cache-Control': 'public, max-age=300' } });
}
